Website = "https://example.com"

[Details]
  Icon = "bf.jpg"
  Name = "Fyne Demo"
  ID = "com.hankmo.app"
  Version = "1.0.0"
  Build = 2

[LinuxAndBSD]
  GenericName = "Web Browser"
  Categories = ["Network"]
  Comment = "View sites on the Internet"
  Keywords = ["browser", "web"]
  ExecParams = "-x 42"
